### ISSUE TITLE
preserve-license-comment don't preserve some license comments perfectly

### ISSUE THREAD

**Issue by saneyuki** [estools/esmangle#101]
## step to reproduce
* `esmangle --preserve-license-comment` for [this file](https://github.com/Gozala/events/blob/master/events.js#L1).
* also `--propagate-license-comment-to-header`.

## actual result
esmangle preserves only these lines :(

```javascript
// Copyright Joyent, Inc. and other Node contributors.
// The above copyright notice and this permission notice shall be included
// NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
function EventEmitter(){this._events=this._events||.............
```

## expected behavior

esmangle should preserve these line comments perfectly!

**Comment by Constellation** [comment]
Please try it on your environment.
If there's no problem, I'll publish esmangle :)

**Comment by saneyuki** [comment]
Great work! I confirm this is fixed in the latest revision.

Thank you!
