### ISSUE TITLE
esmangle is iterating custom circular references inside the AST

### ISSUE THREAD

**Issue by magalhas** [estools/esmangle#103]
I've got my AST instrumented with extra nodes for meta information (such as scopes), and those objects have circular references. What happens is that esmangle iterates over those structures and throws a "Maximum call stack size exceeded" error.

Shouldn't the visit to the tree only crawl known keys?

**Comment by michaelficarra** [comment]
I'd be surprised if this was happening, since esmangle uses estraverse for traversal, and estraverse explicitly visits the appropriate fields for each type of node. Please provide a minimal reproduction case.

**Comment by magalhas** [comment]
A simple scenario is the following one:

```
var ast = {
  "type": "Program",
  "body": [
      {
          "type": "ExpressionStatement",
          "expression": {
              "type": "Identifier",
              "name": "a"
          }
      }
  ]
};
// Just a simple circular reference to replicate the issue
ast.body[0].scope = ast;
require('esmangle').optimize(ast);
```

**Comment by magalhas** [comment]
This is related to the deep copy that estraverse does to the tree. Is it possible to transform the tree without deep copying it? I mean, doing it by reference, that would be awesome and avoid this problem (though this is still a bug I guess).

**Comment by michaelficarra** [comment]
You can pass the `{destructive: true}` option to avoid the deep copy. That should fix your problem. I guess you could still consider the deep copy function buggy because it doesn't handle circular refs. Can you open a new issue for that with a minimal example?

**Comment by magalhas** [comment]
Even with `{destructive: true}` the clone happens, it's being forced in [here](https://github.com/estools/esmangle/blob/master/lib/esmangle.js#L138)

**Comment by michaelficarra** [comment]
Well that's not good.
